# Generated by Django 5.1.5 on 2025-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='response time')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
