# Generated by Django 5.1.5 on 2025-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='response_time',
        ),
        migrations.AlterField(
            model_name='ping',
            name='url',
            field=models.CharField(max_length=225, verbose_name='Ip address or Domain name '),
        ),
    ]
